version: '3'
services:
  app:
    restart: "always"
    image: 'user/app'
    build: 
      context: .
    depends_on:
      - db
  db:
    image: mysql
    restart: "always"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - app