version: '3'
services:
  vira_app:
    deploy:
      replicas: 4
      restart_policy: 
        condition: any
        max_attempts: 10
      update_config:
        parallelism: 2
        delay: 3s
    build: 
      args:
        - NODE_ENV=production
  nginx:
    ports:
      - 80:80