version: '3'
services:
  nginx:
    image: public.ecr.aws/nginx/nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    depends_on:
      - vira_app
  vira_app:
    restart: "always"
    image: 'ibviraco/full_system'
    build: 
      context: .
    depends_on:
      - vira_db
  vira_db:
    image: public.ecr.aws/ubuntu/mysql:latest
    restart: "always"
    volumes:
      - ./vira_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: vira
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 1