
name: CI/CD

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Run composer update
        run: cd vira_dockerized_app && composer update

      - name: Run composer install
        run: cd vira_dockerized_app && composer install
        env:
          APP_ENV: testing

      - name: Run test
        run: cd vira_dockerized_app && php artisan test
        env: 
          APP_KEY: base64:x06N/IsV5iJ+R6TKlr6sC6Mr4riGgl8Rg09XHHnRZQw=
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ibviraco
          password: Vira@5668
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./vira_dockerized_app/
          push: true
          tags: ibviraco/full_system:latest